server:
  port: 8080

spring:
  application:
    name: grade_analysis
  datasource:
    url: jdbc:postgresql://8.137.71.213:5432/zm_app?sslmode=disable&preferQueryMode=simple
    username: remote
    password: 908623
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-aliases-package: com.keinn.grade_analysis_v2.model


logging:
  level:
    org.springframework.jdbc: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: trace